export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',

  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  NO_COMPANY: 'NO_COMPANY',
  ALREADY_IN_COMPANY: 'ALREADY_IN_COMPANY',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  OWNER_ONLY: 'OWNER_ONLY',
  INVALID_MEMBER_ROLE: 'INVALID_MEMBER_ROLE',
  CANNOT_CHANGE_OWN_ROLE: 'CANNOT_CHANGE_OWN_ROLE',
  CANNOT_REMOVE_SELF: 'CANNOT_REMOVE_SELF',
  CANNOT_MODIFY_OWNER: 'CANNOT_MODIFY_OWNER',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
